### ISSUE TITLE
Crashes if state in ndxOutcome is not reached

### ISSUE THREAD

**Issue by torbenott** [KepecsLab/BpodProtocols_Olf2AFC#12]
Protocol crashes if no state specified by find for `ndxOutcome` (`updateCustomDataFields.m`, line 7) is reached. E.g., when no decision was made (no side port entered) and no break fixation (stayed in center port for choice deadline.

Then an error occurs in `updateCustomDataFields.m`, line 42.

**Comment by tsgouvea** [comment]
Well noted. `BpodSystem.Data.Custom.OutcomeRecord` should take a value from a list of mutually-exclusive categories; this _states of interest_ list should cover all possible trial outcomes. I believe this bug arose when a new outcome (`missed_choice`) was introduced in commit 3e6bc1d.
I noticed the outcome `skipped_feedback` is handled in a weird way, different than any other outcome. Will change that too for consistency.

**Comment by torbenott** [comment]
solved with #17
